# This Dockerfile needs tobe located in ./bserv -directory
FROM ubuntu:16.04
WORKDIR /usr/app
RUN apt-get update && apt-get install -y curl git 
RUN git clone https://github.com/docker-hy/backend-example-docker.git 
WORKDIR /usr/app/backend-example-docker
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash
RUN apt-get install -y nodejs
RUN npm install -y
# For Exercise 2.10 FRONT_URL port changed to 80 (as nginx has)
ENV FRONT_URL=http://localhost:80
CMD ["npm", "start"]
EXPOSE 8000
