FROM ubuntu:16.04
WORKDIR /usr
RUN apt-get update && apt-get install -y git
RUN apt-get install -y curl  
RUN git clone https://github.com/docker-hy/frontend-example-docker.git
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash
WORKDIR /usr/frontend-example-docker
RUN apt-get install -y nodejs
RUN npm install -y
CMD ["npm", "start"]
EXPOSE 5000
