FROM ubuntu:16.04
WORKDIR /usr/app
RUN apt-get update && apt-get install -y curl  
COPY backend-example-docker . 
COPY logs.txt .
WORKDIR /usr/app/backend-example-docker
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash
RUN apt-get install -y nodejs
RUN npm install -y
ENV FRONT_URL=http://localhost:8888
CMD ["npm", "start"]
EXPOSE 8000
