# Dockerfile favorite programming tools setup
# Example run:
# docker build -t mytools .
# docker run -it -v $(pwd):/usr/mytools --rm mytools 
# https://hub.docker.com/r/jukidocker/mytools
FROM ubuntu:18.04
WORKDIR /usr/mytools
RUN apt-get update && apt-get install -y git
RUN apt-get install -y curl  
RUN apt-get install -y gcc
RUN apt-get install -y gdb
RUN apt-get install -y valgrind
RUN apt-get install -y g++
RUN apt-get install -y default-jre 
RUN apt-get install -y default-jdk 
RUN apt-get install -y scala 
RUN apt-get install -y gnupg
RUN apt-get install -y vim
RUN apt-get install -y python3
RUN echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
RUN curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add
RUN apt-get update && apt-get install -y sbt 
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install -y nodejs
RUN npm install -y
ENTRYPOINT sh -c "date > start_date.txt;/bin/bash;"
